### ISSUE TITLE
New update GF?

### ISSUE THREAD

**Issue by camitarazaga** [richardW8k/RWListFieldCalculations#12]
It is compatible with new versions of GF? I´m trying it but doesn´t work

**Comment by dhunink** [comment]
Doesn't look like it 😒 
Any updates on this?

**Comment by dhunink** [comment]
I believe I've nailed it down to a recent update of Gravity Perks, not Gravity Forms.
Deactivating and re-activating all Gravity Perks seems to solve the issue.
