### ISSUE TITLE
Column Wrong sum

### ISSUE THREAD

**Issue by riatech** [richardW8k/RWListFieldCalculations#14]
Hi,

I use this plugin together with Drop Down List Field for Gravity Forms by Adrian Gordon.

Form at : http://b.link/fibre48

Previously, i was able to calculate and get the correct column sum for the 3rd column ‘Jumlah’.

But today, i don’t why now i’m getting wrong column sum. I already check everything is in order.

When user click ‘+’ to add another row, the total will automatically add another zero digit. For example, i put 100 in 3rd column in 1st row, after click +, the total will become 1000 ( before i key in value in 2nd row )

Kindly please help me on this problem.

Thank you very much.

**Comment by maxms** [comment]
This is happening for me too. Think it must be something in a recent Gravity Forms update? Here is the form where it was working:
https://www.wmvcf.org/donations-test/ _(version rollback fixed issue so this sample is not working to show the problem 12/5/2018)_

Adding a row adds another zero. Please help! It's Giving Tuesday!!!
@richardW8k 
@ovann86 any chance you might have an idea and be able to help with this? I'd be willing to pay for your time.

**Comment by maxms** [comment]
So, this issue is definitely related to the latest Gravity Forms version update. I tested using the Gravity Forms debug add-on with only GF 2.4.2 and this plugin activated and the issue was present. I reverted back to 2.3.6.8 and the issue is gone.

**@richardW8k please, please, please update your fantastic plugin to work with the latest version. It is the only one that performs this important task.**

**Comment by riatech** [comment]
Yes. Really appreciate if @richardW8k can allocate some time to solve this problem.

Thank you.

**Comment by ovann86** [comment]
Hi all,

I havent looked at your forms, but the first thing I would recommend is try upgrading to Gravity Forms  2.4.2

It includes a fix which may be effecting your calculations ...

> Fixed an incorrect calculation result when the formula includes the merge tag for a standard choice based field; the choice text was being used instead of the choice value.

**Comment by maxms** [comment]
Hi @ovann86. I was updated to 2.4.2 and still seeing the issue.

**Comment by messierlaurent** [comment]
I'm having the same issue here. @ovann86 Can you please fix the plugin for the new GF update? That would be awesome! Thank you so much for your time.

**Comment by richardW8k** [comment]
Please try the latest build. I would also recommend updating Gravity Forms to v2.4.2.2 as it includes a fix for an issue with some calculation results.

**Comment by maxms** [comment]
Hi @richardW8k. Thanks so much for getting on this. That didn't work with GF v2.4.2.2 and RWListFieldCalculations v0.6. See screenshots below. I've reverted back to GF v.2.3.6.8 for now. Really appreciate your time!

<img width="811" alt="screen shot 2018-12-06 at 10 01 09 am" src="https://user-images.githubusercontent.com/6116506/49599460-54280e80-f93e-11e8-80bb-818287bb44e0.png">
<img width="1102" alt="screen shot 2018-12-06 at 10 01 26 am" src="https://user-images.githubusercontent.com/6116506/49599461-54280e80-f93e-11e8-9b56-3be957058c08.png">

**Comment by richardW8k** [comment]
@maxms did you try flushing the browser cache and any caching plugins?

**Comment by messierlaurent** [comment]
Hey @richardW8k , the latest build seems to fix the issue on my end. Thanks for the quick fix, really appreciate it!

**Comment by maxms** [comment]
I did. I will try it again using another browser in a bit.

**Comment by riatech** [comment]
Thank you very much @richardW8k for fixing the problem. Really appreciate it.

@maxms May i know, how do you make the 'donation amount' field only accept number and auto change to zero if the user key-in characters other than number? And how do you auto add the currency sign?

My amount field seem to accept any character and capture it if submitted.

Thank you very much.

![screenshot 2018-12-07 at 2 58 48 am](https://user-images.githubusercontent.com/2073419/49606061-3bb30500-f9cd-11e8-931b-d2510a94ebb4.png)

**Comment by maxms** [comment]
@riatech I am using another plugin:
https://wordpress.org/plugins/list-field-number-format-for-gravity-forms/

**Comment by riatech** [comment]
@maxms Thank you!

👍 @richardW8k

**Comment by maxms** [comment]
Works for me now after clearing browser cache. Thank you SO much, @richardW8k. Cheers!
