### ISSUE TITLE
Form Can't be Edited After Install

### ISSUE THREAD

**Issue by tidusx18** [richardW8k/RWListFieldCalculations#2]
Hi There. I installed on Wordpress with gravity forms 1.9 as directed, but when activated, I can't edit any form. The right side panel with all the fields is no longer displayed and the existing fields in the form can't be edited, moved, etc. Let me know if there is any fix to this.

Thanks!

**Comment by druuid** [comment]
Have the same issue.

**Comment by druuid** [comment]
If you change all of the lines where field->get_input_type() to field->type then it will work.
See documentation on this here:
https://www.gravityhelp.com/documentation/article/gf_field_name/
Try this out.
